version: 4.0.{build}
image: Visual Studio 2017
build_script:
- ps: ./scripts/build.ps1
artifacts:
- path: StarwebSharp/bin/Release/netstandard1.4
  name: netstandard16
- path: StarwebSharp/bin/Release/net45
  name: net461
skip_commits:
  message: /\[skip\]/
  files:
    - readme.md
    - LICENSE
    - .gitignore
    - .vscode/*
    - changelog.md
deploy:
- provider: NuGet
  api_key:
    secure: J2kg5DWTve4wj8MHMV4JUo0TOTMpRB4S64fn4FArSzU1SDHk0hSlfhIELrZFvsnD
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: "Automated AppVeyor release for StarwebSharp v$(APPVEYOR_REPO_TAG_NAME)."
  auth_token:
    secure: rUdMlXxmA59ftJKv2pnCXtgwYhZf2xqyFl0iuAvf6qylYCjM3aF8klLN+711LFV5
  artifact: StarwebSharp.nupkg
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
