version: 4.0.{build}
image: Visual Studio 2017
environment:
  StarwebSharp_API_KEY:
    secure: uF/ZRFFV19rv9tyOtspau/SpzMLQaGFWgBYge7kRC4vk/HHRxKda7BaNi46QhzN/
  StarwebSharp_SECRET_KEY:
    secure: 36pbnnyMdnyPXqzIPVTMNzv8qAzEUs/f7LaheBMCsZHC7EO11llgiMPCwHPhtms4
  StarwebSharp_ACCESS_TOKEN:
    secure: Lt70HrGBrQwKIFWE13zFZRGGwRoPKi1VKjtqBzuR3rdz3w6zD1YXXXe/Zb7xaqX+
  StarwebSharp_MY_STARWEB_URL:
    secure: aWjxVhXImxXX98GcYDmAbGVDxZk9kRaMKGnhm0CLuJ0aFYs0OMNaJOqyT8S4sh9P
build_script:
- ps: ./scripts/build.ps1
test_script:
- ps: ./scripts/test.ps1
artifacts:
- path: StarwebSharp/bin/Release/netstandard1.4
  name: netstandard16
- path: StarwebSharp/bin/Release/net45
  name: net461
skip_commits:
  message: /\[skip\]/
  files:
    - readme.md
    - LICENSE
    - .gitignore
    - .vscode/*
    - changelog.md
deploy:
# - provider: NuGet
#   api_key:
#     secure: uUJ91Fu+H69EdZ8RTYIa7G7UufCgCw1UXfZ2jAOEWJfKi8KNwDTFYaEDQCJS9xOc
#   on:
#     branch: master
#     appveyor_repo_tag: true
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: "Automated AppVeyor release for StarwebSharp v$(APPVEYOR_REPO_TAG_NAME)."
  auth_token:
    secure: OS2yhg1H8KSYenGLlIIvVgsxU1xjtmNRjxrUBuwiWltI3JlvTmaBFijVINnGclbp
  artifact: StarwebSharp.nupkg
  on:
    branch: master
    appveyor_repo_tag: true